SELECT CONCAT(cl.TITLE, '  ',cl.NAME, ' ', cl.SURNAME) as CLIENT, ca.AGGREGATE_TRANSACTION as TRANSACTIONAL_BALANCE, ca2.AGGREGATE_LOAN as LOAN_BALANCE, (ca.AGGREGATE_TRANSACTION + ca2.AGGREGATE_LOAN) as NET_POSITION
from CLIENT cl

LEFT OUTER JOIN (SELECT SUM(tempCa.DISPLAY_BALANCE) as AGGREGATE_TRANSACTION, CLIENT_ID
FROM CLIENT_ACCOUNT tempCa
JOIN ACCOUNT_TYPE tempAt on tempAt.ACCOUNT_TYPE_CODE = tempCa.ACCOUNT_TYPE_CODE
WHERE tempAt.TRANSACTIONAL = true
GROUP BY tempCa.CLIENT_ID) ca on ca.CLIENT_ID=cl.CLIENT_ID

LEFT OUTER JOIN (SELECT SUM(tempCa2.DISPLAY_BALANCE) as AGGREGATE_LOAN, CLIENT_ID
FROM CLIENT_ACCOUNT tempCa2
JOIN ACCOUNT_TYPE tempAt2 on tempAt2.ACCOUNT_TYPE_CODE = tempCa2.ACCOUNT_TYPE_CODE
AND tempAt2.ACCOUNT_TYPE_CODE  in ('HLOAN', 'PLOAN')
GROUP BY tempCa2.CLIENT_ID) ca2 on ca2.CLIENT_ID=cl.CLIENT_ID