SELECT cl.CLIENT_ID, ca.ACC_NUMBER, at.DESCRIPTION, ca.THEMAX
from CLIENT cl
JOIN (SELECT MAX(DISPLAY_BALANCE) as THEMAX, MAX(CLIENT_ACCOUNT_NUMBER) as ACC_NUMBER, MAX(ACCOUNT_TYPE_CODE)  as ACC_TYPE , CLIENT_ID
FROM CLIENT_ACCOUNT GROUP BY CLIENT_ID) ca
on ca.CLIENT_ID = cl.CLIENT_ID
JOIN ACCOUNT_TYPE at on at.ACCOUNT_TYPE_CODE = ca.ACC_TYPE
WHERE at.TRANSACTIONAL = true